/*
 * This file is part of Adblock Plus <https://adblockplus.org/>,
 * Copyright (C) 2006-present eyeo GmbH
 *
 * Adblock Plus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Adblock Plus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.
 */

import { type Info } from "./info.types";

// !! ATTENTION !!
// Do not edit this file!
// This file will be replaced during build time!
// The actual values are in the info.chrome.ts and info.firefox.ts files.

export const info: Info = {
  addonName: "adblockpluschrome",
  baseName: "adblockplus",
  addonVersion: "10.0.0",
  application: "unknown",
  applicationVersion: "100",
  platform: "chromium",
  platformVersion: "100"
};
